trigger:
  batch: true
  branches:
    include: 
    - 'master'
  paths:
   include:
     - platform/*

name: Deploy Hub

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'hub'
  location: 'westeurope'

  hubSub: 'de1b9349-a302-4b0f-98fb-2e6adc5b2d68'
  hubNetworkResourceGroupName: 'hub-network'

pool:
  vmImage: $(vmImageName)

steps:

# Deploy Hub

- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureServiceConnection)
    ScriptType: 'FilePath'
    ScriptPath: $(System.DefaultWorkingDirectory)/.pipelines/deploy.ps1
    ScriptArguments: > # Use this to avoid newline characters in multiline string
      -subscriptionId $(hubSub)
      -resourceGroupName $(hubNetworkResourceGroupName)
      -location $(location)
      -deployment "hub"
      -templateFile $(System.DefaultWorkingDirectory)"/platform/hub.bicep"
      -templateParameterFile $(System.DefaultWorkingDirectory)"/platform/hub-parameters.json"
    azurePowerShellVersion: 'LatestVersion'
  displayName: 'Deploy Hub'