# This is a basic workflow to help you get started with Actions

name: Deploy Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  vmImageName: 'ubuntu-latest'

  location: 'westeurope'

  hubSub: 'de1b9349-a302-4b0f-98fb-2e6adc5b2d68'
  hubNetworkResourceGroupName: 'hub-network'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Use Ubuntu container to execute the action
    runs-on: ubuntu-latest
  
    steps:

      # Checkout code from repo
      - name: Checkout code from repo
        uses: actions/checkout@master
        
      # Login to azure account with service principal from secrets
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
 
      # Deploy the Hub using a PowerShell script
      - name: Deploy Hub
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\scripts\deploy.ps1 -subscriptionId "${{env.hubSub}}" -resourceGroupName "${{env.hubNetworkResourceGroupName}}" -location "${{env.location}}" -deployment "hub" -templateFile './platform/hub.bicep' -templateParameterFile './platform/hub-parameters.json'
          azPSVersion: "latest"
