trigger:
  batch: true
  branches:
    include: 
    - 'master'
  paths:
   include:
     - platform/*

name: Deploy Workload 1

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'spoke1'
  location: 'westeurope'

  workloadSub: '6fd7f490-4be8-41e2-bbdc-7f52d1d7162c'
  workloadNetworkResourceGroupName: 'spoke1-network'
  workloadResourceGroupName: 'spoke1'

  hubSub: 'de1b9349-a302-4b0f-98fb-2e6adc5b2d68'
  hubNetworkResourceGroupName: 'hub-network'

pool:
  vmImage: $(vmImageName)

steps:

# Deploy Virtual Network

- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureServiceConnection)
    ScriptType: 'FilePath'
    ScriptPath: $(System.DefaultWorkingDirectory)/.pipelines/deploy.ps1
    ScriptArguments: > # Use this to avoid newline characters in multiline string
      -subscriptionId $(workloadSub)
      -resourceGroupName $(workloadNetworkResourceGroupName)
      -location $(location)
      -deployment "spoke1-network"
      -templateFile $(System.DefaultWorkingDirectory)"/platform/spoke1-network.bicep"
      -templateParameterFile $(System.DefaultWorkingDirectory)"/platform/spoke1-network-parameters.json"
    azurePowerShellVersion: 'LatestVersion'
  displayName: 'Deploy Virtual Network'

# Deploy Hub Firewall Rules

- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureServiceConnection)
    ScriptType: 'FilePath'
    ScriptPath: $(System.DefaultWorkingDirectory)/.pipelines/deploy.ps1
    ScriptArguments: > # Use this to avoid newline characters in multiline string
      -subscriptionId $(hubSub)
      -resourceGroupName $(hubNetworkResourceGroupName)
      -location $(location)
      -deployment "spoke1-hubfirewall"
      -templateFile $(System.DefaultWorkingDirectory)"/platform/spoke1-hubfirewall.bicep"
      -templateParameterFile $(System.DefaultWorkingDirectory)"/platform/spoke1-hubfirewall-parameters.json"
    azurePowerShellVersion: 'LatestVersion'
  displayName: 'Deploy Hub Firewall Rules'

# Deploy Hub Routing

- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureServiceConnection)
    ScriptType: 'FilePath'
    ScriptPath: $(System.DefaultWorkingDirectory)/.pipelines/deploy.ps1
    ScriptArguments: > # Use this to avoid newline characters in multiline string
      -subscriptionId $(hubSub)
      -resourceGroupName $(hubNetworkResourceGroupName)
      -location $(location)
      -deployment "spoke1-hubrouting"
      -templateFile $(System.DefaultWorkingDirectory)"/platform/spoke1-hubrouting.bicep"
      -templateParameterFile $(System.DefaultWorkingDirectory)"/platform/spoke1-hubrouting-parameters.json"
    azurePowerShellVersion: 'LatestVersion'
  displayName: 'Deploy Hub Routing'

# Deploy Hub Peering

- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureServiceConnection)
    ScriptType: 'FilePath'
    ScriptPath: $(System.DefaultWorkingDirectory)/.pipelines/deploy.ps1
    ScriptArguments: > # Use this to avoid newline characters in multiline string
      -subscriptionId $(hubSub)
      -resourceGroupName $(hubNetworkResourceGroupName)
      -location $(location)
      -deployment "spoke1-hubpeering"
      -templateFile $(System.DefaultWorkingDirectory)"/platform/spoke1-hubpeering.bicep"
      -templateParameterFile $(System.DefaultWorkingDirectory)"/platform/spoke1-hubpeering-parameters.json"
    azurePowerShellVersion: 'LatestVersion'
  displayName: 'Deploy Hub Peering'
